version: '3.7'
services:
  consul:
    image: hashicorp/consul:1.20.3
    ports:
      - "8500:8500"
  
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379