version: '3.7'
services:
  consul:
    image: hashicorp/consul:1.20.3
    ports:
      - "8500:8500"
  
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql

    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: "redis:latest"
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"